### ISSUE TITLE
[CVPR'24 Spotlight] State Space Models for Event Cameras

### ISSUE THREAD

**Issue by NikolaZubic** [xmindflow/Awesome_Mamba#7]
Dear @xmindflow , our work has been a spotlight at CVPR 2024. We would like if you could add it to the list:

https://arxiv.org/abs/2402.15584
https://github.com/uzh-rpg/ssms_event_cameras

Best,
Nikola.

**Comment by moeinheidari7829** [comment]
Hi Nikola, thank you for your interest in our work. We have added your paper to the repository.
